trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
  - template: ci/job-rustfmt.yml
  - template: ci/job-check.yml
    parameters:
      toolchain: nightly
  - template: ci/job-test.yml
    parameters:
      name: test_stable
      toolchain: stable
  - template: ci/job-test.yml
    parameters:
      name: test_nightly
      toolchain: nightly
